routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\ArtistController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::resource('artist', ArtistController::class);

Route::resource('country', CountryController::class);

Route::resource('cinemas', CinemasController::class);

Route::resource('salles', SallesController::class);

Route::resource('seances', SeancesController::class);


Route::prefix('movie')->middleware('auth')->group(function () {

    Route::get('actors/{movie}',[MovieController::class, 'actors'])->name('movie.actors');
    Route::post('attach/{movie}',[MovieController::class, 'attach'])->name('movie.attach');
    Route::delete('detach/{movie}/{artist}',[MovieController::class, 'detach'])->name('movie.detach');

});

Route::resource('movie', MovieController::class);

require __DIR__.'/auth.php';

app/Models/Seances.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Seances extends Model
{
    use HasFactory;

    public function Cinemas_diffuse()
    {
        return $this->hasMany(Cinemas::class);
    }

    public function Salles_diffuse()
    {
        return $this->hasMany(Salles::class);
    }
}

app/Http/Controllers/SeancesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\MovieRequest;
use App\Models\Artist;
use App\Models\Country;
use App\Models\Movie;
use App\Notifications\MovieCreated;
use App\Models\Cinemas;
use App\Models\Seances;
use App\Models\Salles;

class SeancesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('seances.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/seances/create.blade.php
<x-app>
    <x-slot name="page_title">Create a Seance</x-slot>

    <form method="POST" action="{{ route('seance.store') }}">
        {{ csrf_field() }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="" required class="block appearance-none w-full py-1 px-2 mb-1 text-base leading-normal bg-white text-grey-darker border border-grey rounded" />
            <x-error name="name"></x-error>
        </p>
        <p>
            <label for="birthdate">Date</label>
            <input type="text" name="birthdate" id="birthdate" value="" class="block appearance-none w-full py-1 px-2 mb-1 text-base leading-normal bg-white text-grey-darker border border-grey rounded" />
            <x-error name="birthdate"></x-error>
        </p>

        <button type="submit" class="inline-block align-middle text-center select-none border font-normal whitespace-no-wrap py-2 px-4 rounded text-base leading-normal no-underline text-blue-lightest bg-blue hover:bg-blue-light py-3 px-4 text-xl leading-tight">Create</button>
    </form>
</x-app>

resources/views/seances/edit.blade.php
<x-app>
    <x-slot name="page_title">Edit {{ $seance->name . ' a ' . $seance->birthdate }}</x-slot>

    <form method="POST" action="{{ route('seances.update', $seances->id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}

        <p>
            <label for="birthdate">Date</label>
            <input type="text" name="birthdate" id="birthdate" value="{{ $artist->birthdate }}" class="block appearance-none w-full py-1 px-2 mb-1 text-base leading-normal bg-white text-grey-darker border border-grey rounded" />
            <x-error name="birthdate"></x-error>
        </p>

        <button type="submit" class="focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">
            Update
        </button>
    </form>
</x-app>

resources/views/seances/index.blade.php
<x-app>
    <x-slot name="page_title">Seances</x-slot>

    <a href="{{ route('artist.create') }}" class="align-left focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg">
        {{ __('New') }}
    </a>

    <table class="divide-y divide-gray-200 mt-4">
        <thead class="bg-gray-50">
            <tr>
                <th class="text-left px-2 py-3">{{ __('Name') }}</th>
                <th class="text-left px-2 py-3">{{ __('Birthdate') }}</th>
            </tr>
        </thead>
        <tbody class="bg-white text-xs divide-y divide-gray-200">
            @foreach($seances as $seance)
            <tr>
                <td class="px-2 py-4">{{ $seance->name }}</td>
                <td class="px-2 py-4">{{ $seance->birthdate }}</td>
                <td class="px-2 py-4">
                    @can('update', $seance)
                    <a href="{{ route('seance.edit', $seance->name) }}" class="focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">
                        {{ __('Edit') }}
                    </a>
                    @endcan

                    @can('delete', $seance)
                    <a href="{{ route('seance.destroy', $artist->name) }}" class="delete focus:outline-none text-white text-sm py-2.5 px-5 ml-2 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg">
                        {{ __('Delete') }}
                    </a>
                    @endcan
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{ $seances->links() }}

    <script>
    // Récupération du token
    let token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

    // Ajout des événements
    document.querySelectorAll('.delete').forEach(item => {
      item.addEventListener('click', event => {
        event.preventDefault();

        // Requête AJAX de suppression
        fetch(event.target.href, {
          headers: {
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRF-TOKEN': token
          },
          method: 'DELETE',
        })
        .then((data) => {
            event.target.closest('tr').remove();
        });
      })
    });
    </script>

</x-app>